/**
 * MegaOTT API Service
 * 
 * Modular service for interacting with the MegaOTT IPTV panel API.
 * Handles subscription creation, retrieval, extension, activation, and deactivation.
 * 
 * API Documentation: https://megaott.net/docs/
 * Base URL: https://megaott.net/api/v1
 * Auth: OAuth2 Bearer token (Account Settings > API Keys)
 * Content-Type: application/x-www-form-urlencoded
 */

export interface MegaOTTConfig {
  apiUrl: string;       // e.g., "https://megaott.net/api/v1"
  apiToken: string;     // API token from Panel dashboard > Account Settings > API Keys
}

export interface CreateSubscriptionParams {
  /** Subscription type: "M3U", "mag", or "enigma" (default: "M3U") */
  type?: 'M3U' | 'mag' | 'enigma';
  /** Username for the subscription (required for M3U). Auto-generated if not provided. */
  username?: string;
  /** MAC address (required for mag/enigma subscriptions) */
  macAddress?: string;
  /** Package ID from MegaOTT panel (required) */
  packageId: number;
  /** Maximum simultaneous connections (default: 1) */
  maxConnections?: number;
  /** Template ID for the subscription (optional) */
  templateId?: number;
  /** Forced country code, e.g. "US", "FR", or "ALL" for no restriction (default: "ALL") */
  forcedCountry?: string;
  /** Whether to include adult bouquets (default: false) */
  adult?: boolean;
  /** Additional notes for the subscription */
  note?: string;
  /** WhatsApp or Telegram number for the customer */
  whatsappTelegram?: string;
  /** Whether to enable VPN (default: false) */
  enableVpn?: boolean;
  /** Whether the subscription is paid (default: false) */
  paid?: boolean;
}

export interface SubscriptionCredentials {
  /** Subscription ID in MegaOTT panel */
  subscriptionId: string;
  /** Username for IPTV login */
  username: string;
  /** Password for IPTV login (auto-generated by MegaOTT) */
  password: string;
  /** DNS link / server URL for the subscription */
  serverUrl: string;
  /** DNS link for Samsung and LG devices */
  serverUrlSamsungLg: string;
  /** Full M3U playlist URL (constructed from dns_link + credentials) */
  playlistUrl: string;
  /** Expiration date string from MegaOTT */
  expDate: string;
  /** Subscription type: M3U, mag, or enigma */
  playlistType: string;
  /** Portal link (for mag/enigma) */
  portalLink: string | null;
}

/** Raw subscription response from MegaOTT API */
interface MegaOTTSubscriptionResponse {
  type: string;
  id: number;
  username: string;
  password: string;
  mac_address: string | null;
  package: { id: number; name: string };
  template: { id: number; name: string } | null;
  max_connections: number;
  forced_country: string;
  adult: boolean;
  note: string;
  whatsapp_telegram: string;
  paid: boolean;
  expiring_at: string;
  dns_link: string;
  dns_link_for_samsung_lg: string;
  portal_link: string | null;
}

export interface MegaOTTError {
  status: boolean;
  message: string;
}

/**
 * Common headers for all MegaOTT API requests.
 * User-Agent is REQUIRED -- MegaOTT's CloudFlare blocks requests without it (403 Forbidden).
 */
function getHeaders(apiToken: string): Record<string, string> {
  return {
    'Authorization': `Bearer ${apiToken}`,
    'Accept': 'application/json',
    'User-Agent': 'Mozilla/5.0 (compatible; IPTVSmarters/1.0)',
  };
}

/**
 * Generate a random alphanumeric uppercase string for usernames
 */
function generateRandomUsername(length: number): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

/**
 * Construct the full M3U playlist URL from dns_link and credentials
 */
function buildPlaylistUrl(dnsLink: string, username: string, password: string): string {
  const baseUrl = dnsLink.replace(/\/$/, '');
  return `${baseUrl}/get.php?username=${username}&password=${password}&type=m3u_plus&output=ts`;
}

/**
 * Map raw MegaOTT API response to SubscriptionCredentials
 */
function mapResponseToCredentials(data: MegaOTTSubscriptionResponse): SubscriptionCredentials {
  const serverUrl = data.dns_link || '';
  const serverUrlSamsungLg = data.dns_link_for_samsung_lg || '';
  const playlistUrl = serverUrl
    ? buildPlaylistUrl(serverUrl, data.username, data.password)
    : '';

  return {
    subscriptionId: data.id.toString(),
    username: data.username,
    password: data.password,
    serverUrl,
    serverUrlSamsungLg,
    playlistUrl,
    expDate: data.expiring_at || '',
    playlistType: data.type || 'M3U',
    portalLink: data.portal_link,
  };
}

/**
 * Create a subscription on the MegaOTT panel
 * 
 * POST /v1/subscriptions
 * Content-Type: application/x-www-form-urlencoded
 * 
 * The API auto-generates the password. Expiration is determined by the package_id.
 * 
 * @see https://megaott.net/docs/subscriptions
 */
export async function createSubscription(
  config: MegaOTTConfig,
  params: CreateSubscriptionParams
): Promise<SubscriptionCredentials> {
  const username = params.username || generateRandomUsername(8);
  const type = params.type || 'M3U';

  const apiUrl = config.apiUrl.replace(/\/$/, '');

  // Build form data as required by the MegaOTT API
  const formData = new URLSearchParams();
  formData.append('type', type);
  formData.append('username', username);
  formData.append('package_id', params.packageId.toString());
  formData.append('max_connections', (params.maxConnections || 1).toString());

  // MegaOTT only accepts "ALL" or specific 2-letter codes like "US", "GB", etc.
  // It does NOT accept "FR" — always fall back to "ALL" if unsure.
  const country = params.forcedCountry?.toUpperCase() || 'ALL';
  formData.append('forced_country', country === 'ALL' ? 'ALL' : country);

  formData.append('adult', params.adult ? '1' : '0');
  formData.append('enable_vpn', params.enableVpn ? '1' : '0');
  formData.append('paid', params.paid ? '1' : '0');

  // whatsapp_telegram is REQUIRED by MegaOTT and must be a non-empty string
  const phone = params.whatsappTelegram?.trim();
  formData.append('whatsapp_telegram', phone && phone.length > 0 ? phone : '0000000000');

  // Optional fields
  if (params.macAddress) {
    formData.append('mac_address', params.macAddress);
  }
  if (params.templateId) {
    formData.append('template_id', params.templateId.toString());
  }
  if (params.note) {
    formData.append('note', params.note);
  }

  try {
    console.log(`[MegaOTT] Creating subscription: type=${type}, username=${username}, package_id=${params.packageId}`);

    const response = await fetch(`${apiUrl}/subscriptions`, {
      method: 'POST',
      headers: getHeaders(config.apiToken),
      body: formData,
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('[MegaOTT] API Error:', response.status, errorText);
      throw new Error(`MegaOTT API error: ${response.status} - ${errorText}`);
    }

    const data: MegaOTTSubscriptionResponse = await response.json();
    const credentials = mapResponseToCredentials(data);

    console.log(`[MegaOTT] Subscription created: id=${credentials.subscriptionId}, username=${credentials.username}, expires=${credentials.expDate}`);

    return credentials;
  } catch (error) {
    console.error('[MegaOTT] Failed to create subscription:', error);
    throw error;
  }
}

/**
 * Retrieve a subscription from MegaOTT
 * 
 * GET /v1/subscriptions/:id
 * 
 * @see https://megaott.net/docs/subscriptions
 */
export async function getSubscription(
  config: MegaOTTConfig,
  subscriptionId: string
): Promise<SubscriptionCredentials | null> {
  try {
    const apiUrl = config.apiUrl.replace(/\/$/, '');

    const response = await fetch(`${apiUrl}/subscriptions/${subscriptionId}`, {
      method: 'GET',
      headers: getHeaders(config.apiToken),
    });

    if (!response.ok) {
      console.error('[MegaOTT] Failed to get subscription:', response.status);
      return null;
    }

    const data: MegaOTTSubscriptionResponse = await response.json();
    return mapResponseToCredentials(data);
  } catch (error) {
    console.error('[MegaOTT] Failed to get subscription:', error);
    return null;
  }
}

/**
 * Extend a subscription on MegaOTT
 * 
 * POST /v1/subscriptions/{id}/extend
 * 
 * @see https://megaott.net/docs/subscriptions
 */
export async function extendSubscription(
  config: MegaOTTConfig,
  subscriptionId: string,
  packageId: number,
  paid: boolean = false
): Promise<{ status: boolean; message: string; newExpirationDate?: string }> {
  try {
    const apiUrl = config.apiUrl.replace(/\/$/, '');

    const formData = new URLSearchParams();
    formData.append('package_id', packageId.toString());
    formData.append('paid', paid ? '1' : '0');

    const response = await fetch(`${apiUrl}/subscriptions/${subscriptionId}/extend`, {
      method: 'POST',
      headers: getHeaders(config.apiToken),
      body: formData,
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('[MegaOTT] Failed to extend subscription:', response.status, errorText);
      throw new Error(`MegaOTT API error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    console.log(`[MegaOTT] Subscription ${subscriptionId} extended: ${data.message}`);

    return {
      status: data.status,
      message: data.message,
      newExpirationDate: data.new_expiration_date,
    };
  } catch (error) {
    console.error('[MegaOTT] Failed to extend subscription:', error);
    throw error;
  }
}

/**
 * Deactivate a subscription on MegaOTT
 * 
 * POST /v1/subscriptions/{id}/deactivate
 * 
 * @see https://megaott.net/docs/subscriptions
 */
export async function deactivateSubscription(
  config: MegaOTTConfig,
  subscriptionId: string
): Promise<{ status: boolean; message: string }> {
  try {
    const apiUrl = config.apiUrl.replace(/\/$/, '');

    const response = await fetch(`${apiUrl}/subscriptions/${subscriptionId}/deactivate`, {
      method: 'POST',
      headers: getHeaders(config.apiToken),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('[MegaOTT] Failed to deactivate subscription:', response.status, errorText);
      throw new Error(`MegaOTT API error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    console.log(`[MegaOTT] Subscription ${subscriptionId} deactivated: ${data.message}`);

    return { status: data.status, message: data.message };
  } catch (error) {
    console.error('[MegaOTT] Failed to deactivate subscription:', error);
    throw error;
  }
}

/**
 * Activate a previously deactivated subscription on MegaOTT
 * 
 * POST /v1/subscriptions/{id}/activate
 * 
 * @see https://megaott.net/docs/subscriptions
 */
export async function activateSubscription(
  config: MegaOTTConfig,
  subscriptionId: string
): Promise<{ status: boolean; message: string }> {
  try {
    const apiUrl = config.apiUrl.replace(/\/$/, '');

    const response = await fetch(`${apiUrl}/subscriptions/${subscriptionId}/activate`, {
      method: 'POST',
      headers: getHeaders(config.apiToken),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('[MegaOTT] Failed to activate subscription:', response.status, errorText);
      throw new Error(`MegaOTT API error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    console.log(`[MegaOTT] Subscription ${subscriptionId} activated: ${data.message}`);

    return { status: data.status, message: data.message };
  } catch (error) {
    console.error('[MegaOTT] Failed to activate subscription:', error);
    throw error;
  }
}

/**
 * Get authenticated user info (username, credit balance)
 * 
 * GET /v1/user
 * 
 * Useful to check remaining credits in the admin panel.
 */
export async function getUserInfo(
  config: MegaOTTConfig
): Promise<{ id: number; username: string; credit: number } | null> {
  try {
    const apiUrl = config.apiUrl.replace(/\/$/, '');

    const response = await fetch(`${apiUrl}/user`, {
      method: 'GET',
      headers: getHeaders(config.apiToken),
    });

    if (!response.ok) {
      console.error('[MegaOTT] Failed to get user info:', response.status);
      return null;
    }

    return await response.json();
  } catch (error) {
    console.error('[MegaOTT] Failed to get user info:', error);
    return null;
  }
}

/**
 * Get MegaOTT configuration from payment settings
 */
export function getMegaOTTConfig(settings: Record<string, string>): MegaOTTConfig | null {
  const apiUrl = settings['megaott_api_url'];
  const apiToken = settings['megaott_api_token'];

  if (!apiUrl || !apiToken) {
    console.error('[MegaOTT] Missing API URL or token in settings');
    return null;
  }

  return { apiUrl, apiToken };
}
